if exists('g:loaded_html_renderer')
    finish
endif
let g:loaded_html_renderer = 1

function! s:Requirehtmlrenderer(host) abort
    return sockconnect('pipe', '.nvim_plugin_sock', {'rpc': v:true})
endfunction

call remote#host#Register('htmlrenderer', 'x', function('s:Requirehtmlrenderer'))
" Autogenerated
call remote#host#RegisterPlugin('htmlrenderer', '0', [
\ {'type': 'function', 'name': 'Hello', 'sync': 1, 'opts': {}},
\ ])
